import type { TranscriptionRecord } from '@/types';
import { LANGUAGE_LABELS } from '@/types';

export function downloadTranscription(record: TranscriptionRecord): void {
  const blob = new Blob([record.text], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const timestamp = new Date(record.createdAt).toISOString().replace(/:/g, '-').replace(/\.\d{3}Z$/, '');
  const a = document.createElement('a');
  a.href = url;
  a.download = `transcription-${record.language}-${timestamp}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

export function downloadReport(record: TranscriptionRecord): void {
  const date = new Date(record.createdAt).toLocaleString();
  const lang = LANGUAGE_LABELS[record.language];
  const duration = `${Math.floor(record.durationSeconds / 60)}m ${record.durationSeconds % 60}s`;

  const report = `
=====================================
         TRANSCRIPTION REPORT
=====================================

Date:       ${date}
Language:   ${lang}
Duration:   ${duration}

-------------------------------------
TRANSCRIPT
-------------------------------------

${record.text}

-------------------------------------
STATISTICS
-------------------------------------

Word Count:    ${record.text.trim().split(/\s+/).filter(Boolean).length}
Characters:    ${record.text.length}

=====================================
Generated by ListenAI
=====================================
`.trim();

  const blob = new Blob([report], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const timestamp = new Date(record.createdAt).toISOString().replace(/:/g, '-').replace(/\.\d{3}Z$/, '');
  const a = document.createElement('a');
  a.href = url;
  a.download = `report-${record.language}-${timestamp}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

export function getLanguageLabel(record: TranscriptionRecord): string {
  return LANGUAGE_LABELS[record.language];
}
